stages:
  - build
  - deploy

variables:
  PROJECT_NAME: drupalwxt/site-wxt

image: drupalwxt/gitlab-ci

services:
  - docker:dind

before_script:
  - docker info

build_job:
  stage: build
  script:
   - echo "Building $PROJECT_NAME test runner"
   - composer global require "hirak/prestissimo:^0.3"
   - composer install --prefer-dist --no-interaction
   - export COMPOSE_HTTP_TIMEOUT=200
   - docker-compose --version
   # Build out the Drupal infrastructure.
   # make build can be avoided if leveraging Docker Hub.
   # - make build
   - docker-compose -f docker-compose-ci.yml up -d
   - docker ps -a
   - sleep 10
   - make drupal_install
   - make test

# deploy_release:
#   stage: deploy
#   script:
#     - composer install --prefer-dist --no-interaction
#     - ./vendor/bin/dep --file=./docker/deploy.php develop
#   dependencies:
#     - build_job
#   only:
#     - /v[0-9].*$/
